import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { LockKeyhole } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { supabase } from "@/integrations/supabase/client";
import { lovable } from "@/integrations/lovable";

export const Route = createFileRoute("/auth")({
  head: () => ({ meta: [{ title: "Kuingia kwa Wasimamizi | Ofisi ya Mbunge" }, { name: "description", content: "Eneo salama la wasimamizi wa tovuti." }, { property: "og:title", content: "Kuingia kwa Wasimamizi" }, { property: "og:description", content: "Eneo salama la usimamizi wa maudhui." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: AuthPage,
});
function AuthPage(){const[mode,setMode]=useState<"signin"|"signup">("signin");const[loading,setLoading]=useState(false);const navigate=useNavigate();async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);const fd=new FormData(e.currentTarget);const email=String(fd.get("email"));const password=String(fd.get("password"));try{if(mode==="signin"){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await navigate({to:"/admin"});}else{const{data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+"/auth"}});if(error)throw error;if(!data.session){toast.success("Angalia barua pepe kuthibitisha akaunti. Ruhusa ya usimamizi hutolewa na msimamizi mkuu.");setMode("signin");}}}catch(err){toast.error(err instanceof Error?err.message:"Jaribu tena.");}finally{setLoading(false);}}async function google(){const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin+"/auth"});if(result.error)toast.error(result.error.message);else if(!result.redirected)await navigate({to:"/admin"});}return <section className="min-h-[70vh] bg-secondary px-4 py-16"><div className="mx-auto max-w-md border border-border bg-background p-7 shadow-institutional"><LockKeyhole className="size-8 text-primary"/><h1 className="mt-5 font-display text-2xl font-bold">{mode==="signin"?"Ingia kwenye Usimamizi":"Fungua Akaunti"}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Akaunti mpya haitapewa ruhusa ya usimamizi hadi idhinishwe rasmi.</p><form onSubmit={submit} className="mt-7 space-y-5"><div><Label htmlFor="email">Barua pepe</Label><Input id="email" name="email" type="email" required className="mt-2"/></div><div><Label htmlFor="password">Nenosiri</Label><Input id="password" name="password" type="password" required minLength={8} className="mt-2"/></div><Button className="w-full" disabled={loading}>{loading?"Subiri...":mode==="signin"?"Ingia":"Fungua Akaunti"}</Button></form><div className="my-5 flex items-center gap-3 text-xs text-muted-foreground"><span className="h-px flex-1 bg-border"/>AU<span className="h-px flex-1 bg-border"/></div><Button type="button" variant="outline" className="w-full" onClick={google}>Endelea na Google</Button><Button type="button" variant="link" className="mt-3 w-full" onClick={()=>setMode(mode==="signin"?"signup":"signin")}>{mode==="signin"?"Fungua akaunti":"Nina akaunti tayari"}</Button></div></section>}